apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-khxd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-khxd@sha256:bc7b8d8c83b86ffa2df9a5a0df3eb56d7220772e5cd4d676d87a87855fc85359
        name: my-nodejs
        resources: {}
status: {}
